# DYNAMIC_MACRO_ENABLE = no
# COMBO_ENABLE = no
# KEY_OVERRIDE_ENABLE = no

#HAPTIC FEEBACK
# HAPTIC_ENABLE = no

# VIA(L)
# VIA_ENABLE = yes
# VIAL_ENABLE = yes
# VIAL_ENCODERS_ENABLE = yes
# VIALRGB_ENABLE = yes
