# EXTRAKEY_ENABLE = yes
# DYNAMIC_MACRO_ENABLE = yes
# COMBO_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes

# OLED
OLED_ENABLE = yes
OLED_DRIVER = ssd1306

# Encoders
ENCODER_ENABLE = yes
# ENCODER_MAP_ENABLE = yes

#HAPTIC FEEBACK
# HAPTIC_ENABLE = yes
# HAPTIC_DRIVER = drv2605l

#PER KEY RGB
# RGB_MATRIX_ENABLE = yes

#AUDIO
# AUDIO_ENABLE = yes
MUSIC_ENABLE = no

# # Tri Layer
# TRI_LAYER_ENABLE = yes
# TRI_LAYER_LOWER_LAYER = 1
# TRI_LAYER_RAISE_LAYER = 2
# TRI_LAYER_ADJUST_LAYER = 3

# VIA(L)
# VIA_ENABLE = yes
# VIAL_ENABLE = yes
# VIAL_ENCODERS_ENABLE = yes
# VIALRGB_ENABLE = yes


